# Install Jenkins.
- include_tasks: install.yml


# Create Jenkins service.
- include_tasks: service.yml


# Install plugins.
- include_tasks: plugins.yml


# Create Jenkins CasC file.
- name: Copy Jenkins CasC file
  copy:
    src: jenkins.yaml
    dest: "{{ jenkins_home }}/jenkins.yaml"
    owner: jenkins
    group: jenkins
    mode: 0755


# Create Jenkins jobs.
- include_tasks: jobs.yml

- name: Restart Jenkins
  service: name=jenkins state=restarted