# Install docker
- include_tasks: install.yml


# Start docker service
- include_tasks: service.yml


# Add jenkins user to docker group
- name: Add user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes